name: Build and deploy Node.js app to Azure Web App - DCT-ANG
on:
  push:
    branches:
      - master

env:
  AZURE_WEBAPP_NAME: "DCT-ANG"    # set this to your application's name
  AZURE_WEBAPP_NAME_PRD: ""    # set this for name of production API
  AZURE_WEBAPP_PACKAGE_PATH: "."      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '14.16.0'                        # set this to the node version to use
  RESOURCEGROUPNAME: "DCT_ANG"
  LOCATION: "South Brazil"
  HOSTINGPLANNAME: "ASP-DCTANG-9a56"
  APPINSIGHTLOCATION: "Brazil Southeast"
  SKU: "B1 1"

jobs:
  build:
    name: Build and Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: npm install, build, and test
        run: |
          npm install @angular/cli
          ng --version
          npm install
          npm run build --if-present

      - name: Creating artifact directories
        run: |
          mkdir buildartifacts

      # Archive build artifact
      - name: Archive Application
        run: |
          zip -qq -r ./buildartifacts/Application.zip .

      # Uploading application to build artifact
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: buildartifacts
          path: buildartifacts

  DeployQA:
    name: Deploy to Azure Web Angular QA
    needs: build    
    runs-on: ubuntu-latest    
    steps:
      # Downloading build artifact
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: buildartifacts
          path: buildartifacts

       # Uzipping build artifacts
      - name: unzipping build artifact
        run: |
          unzip -qq ./buildartifacts/Application.zip -d .

      # Login to azure
      # - name: Login to Azure
      #   uses: azure/login@v1
      #   continue-on-error: false
      #   with:
      #     creds: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_FA31D2F0DEAE448786CC71553E739DF0 }}

      # Deploy web app on azure
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'DCT-ANG'
          #slot-name: 'QA'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_FA31D2F0DEAE448786CC71553E739DF0 }}
          package: .

  DeployPRD:
    name: Deploy to Azure Web Angular PRD
    needs: DeployQA  
    runs-on: ubuntu-latest
    environment:     
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
    # Downloading build artifact
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2
      continue-on-error: false
      with:
        name: buildartifacts
        path: buildartifacts

    # Uzipping build artifacts
    - name: unzipping build artifact
      run: |
        unzip -qq ./buildartifacts/Application.zip -d .

    # Deploy web app on azure
    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: 'DCT-ANG-PROD'
        slot-name: 'Production'
        publish-profile: ${{ secrets }}
        package: .
