name: Build and deploy Node.js app to Azure Web App - DCT-ANG
on:
  push:
    branches:
      - master

env:
  AZURE_WEBAPP_NAME: "DCT-ANG"    # set this to your application's name
  AZURE_WEBAPP_NAME_PRD: "OfficialDCT"    # set this for name of production API  
  NODE_VERSION: '14.16.0'                        # set this to the node version to use
  RESOURCEGROUPNAME: "DCT_ANG"
  LOCATION: "South Brazil"
  HOSTINGPLANNAME: "ASP-DCTANG-9a56"
  APPINSIGHTLOCATION: "Brazil Southeast"
  SKU: "B1 1"

jobs:
  build:
    name: Build and Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present

      - name: Creating artifact directories
        run: |
          mkdir buildartifactsQA
          mkdir buildartifactsPROD

      # Archive build artifact
      - name: Archive Application
        run: |
          zip -qq -r ./buildartifactsQA/Application.zip .
          zip -qq -r ./buildartifactsPROD/Application.zip .

      # Uploading application to build artifact QA
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: buildartifactsQA
          path: buildartifactsQA

      # Uploading application to build artifact PROD
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: buildartifactsPROD
          path: buildartifactsPROD

  DeployQA:
    name: Deploy to Azure Web Angular QA
    needs: build    
    runs-on: ubuntu-latest    
    steps:
      # Downloading build artifact
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: buildartifactsQA
          path: buildartifactsQA

       # Uzipping build artifacts
      - name: unzipping build artifact
        run: |
          unzip -qq ./buildartifactsQA/Application.zip -d .     

      # Deploy web app on azure
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'DCT-ANG'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_FA31D2F0DEAE448786CC71553E739DF0 }}
          package: ./distQA/DCT-ANG

  DeployPRD:
    name: Deploy to Azure Web Angular PRD
    needs: [DeployQA]  
    environment: Production
    runs-on: ubuntu-latest   
    steps:    
      # Downloading build artifact
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2
        with:
          name: buildartifactsPROD
          path: buildartifactsPROD

      # Uzipping build artifacts
      - name: unzipping build artifact
        run: |
          unzip -qq ./buildartifactsPROD/Application.zip -d .

      # Deploy web app on azure
      - name: 'Deploy to Azure WebApp'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ env.AZURE_WEBAPP_NAME_PRD }}
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_PROD }}
          package: ./distPROD/DCT-ANG
